### ISSUE TITLE
Fullstack User Auth MVP

### ISSUE THREAD

**Issue by crgee1** [crgee1/FSP#2]
Hi Andy,

I finished the User Auth MVP, please review at your convenience.

[Streben Live Demo](https://streben.herokuapp.com/#/)

## New account creation, login, and guest/demo login

- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] Users can't use certain features without logging in

### Functionality/Structure:
- [x] Logged in user can currently visit your splash page. They should be redirected to their dashboard
- [x] Please edit your "/" landing page to mirror Strava's landing page for https://www.strava.com/

### Styling:
- [x] increase all sizing of your login/signup form, and move closer to the navbar
- [x] increase height and font sizing of your navbar
- [x] Incorporate a button that mirrors the "Login in with Facebook" button, that uses your demo account
- add styling to your inputs to change background to grey on focus

**Comment by minucos** [comment]
Hi Chris,

Looking great!

I've added a couple check boxes to your issue above with my notes on any changes. Nothing major so shouldn't take you long. Once you are done just drop another comment here and I'll check them off.

Great job.

Andy

**Comment by crgee1** [comment]
I have attempted to address the additional check marks for your review. Thank you.
